// Bundle the Worker into ONE file for the Cloudflare dashboard editor
// (Workers & Pages → your worker → Edit code → paste). No esbuild needed:
// the three modules have no name collisions, so this strips import/export
// lines and concatenates them. Run: node wire/build.mjs → wire/dist/worker.js
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const strip = (src) => src
  .replace(/^import .*?;\s*$/gm, '')                 // imports (single line, all of ours are)
  .replace(/^export default /m, '__DEFAULT__ = ')     // index's default export → assigned below
  .replace(/^export (async function|function|const|let)/gm, '$1');
const core = strip(readFileSync(join(here, '..', 'tools', 'fit-push-core.mjs'), 'utf8'));
const webpush = strip(readFileSync(join(here, 'src', 'webpush.mjs'), 'utf8'));
const index = strip(readFileSync(join(here, 'src', 'index.mjs'), 'utf8'));
const out = `// ppc-wire — single-file build for the Cloudflare dashboard. GENERATED by
// wire/build.mjs from tools/fit-push-core.mjs + wire/src/*.mjs — edit those,
// then run \`node wire/build.mjs\` and paste this file again.
// Built ${new Date().toISOString()}
let __DEFAULT__;

/* ===== tools/fit-push-core.mjs ===== */
${core}

/* ===== wire/src/webpush.mjs ===== */
${webpush}

/* ===== wire/src/index.mjs ===== */
${index}

export default __DEFAULT__;
`;
mkdirSync(join(here, 'dist'), { recursive: true });
writeFileSync(join(here, 'dist', 'worker.js'), out);
console.log('wrote wire/dist/worker.js', out.length, 'bytes');
